### PR TITLE
icicle v2 integration

### PR DESCRIPTION
**Pull request by emirsoyturk**
**Summary:**  
This PR updates the existing ICICLE MSM operations to use the latest version of ICICLE v2 and also enables NTT and INTT operations to be executed on the GPU via ICICLE.

### CODE REVIEW

**Comment by alexander-camuto** [comment]
@emirsoyturk tysm for your PR do you mind rebasing with #14 so that you get the latest performance updates / new msm

**Comment by emirsoyturk** [comment]
Hey, @alexander-camuto. I am going to apply changes on the main branch but i cannot run tests in the latest version. It throws couple errors. `cargo bench` and `cargo test` don't work.

**Comment by alexander-camuto** [comment]
Will take a look :)

**Comment by alexander-camuto** [comment]
@emirsoyturk patched ! thank you

**Pull request closed without merging**
